### ISSUE TITLE
Push to NuGet.org?

### ISSUE THREAD

**Issue by gep13** [hawker-am/Cake.ScheduledTasks#1]
@hawker-am just wanted to reach out to see what the current state of this addin is.  Is it in a position to be pushed to NuGet.org?

We had a community member ask about Scheduled Tasks within Cake, and I pointed them here, but then they noticed that it hadn't been pushed to NuGet.org.

**Comment by hawker-am** [comment]
@gep13 Thanks for getting in touch. I have stopped working on this project, but I would be happy to push it to NuGet for others to use.

**Comment by gep13** [comment]
@hawker-am if you could, that would be great.

Also, if this project is something that you are no longer working on, it would seem a shame to waste the effort that you have put in.  Would you think about moving the repository into the Cake Contrib Organisation, so that others who are interested in helping to maintain it could help out?

**Comment by hawker-am** [comment]
I have pushed the package to https://www.nuget.org/packages/Cake.ScheduledTasks/1.0.0
I'm happy to move the repo to the cake contrib org, how do i go about that? Shall i transfer the repo to you?

**Comment by gep13** [comment]
>@hawker-am said...
I'm happy to move the repo to the cake contrib org, how do i go about that? Shall i transfer the repo to you?

Yes, the easiest way that I have found to make this happen is for you to transfer the repo to my personal account (gep13) and from there, I can move it into the repository.  Let me know if you would like to go ahead with this.  Also, if you could, could you add the `cake-contrib` user as a co-owner of the NuGet Package on NuGet.org?  This will help with ongoing maintenance.

Thanks again!

**Comment by gep13** [comment]
@hawker-am thanks again for pushing this to NuGet.org.

I will close this issue out, for now.
