### ISSUE TITLE
Move to Cake-Contrib Organisation

### ISSUE THREAD

**Issue by gep13** [hawker-am/Cake.ScheduledTasks#3]
@hawker-am you mentioned in another issue that you might be interested in moving this addin into the Cake-Contrib Organisation.

Please let me know if this is something that you would like to continue with.

**Comment by hawker-am** [comment]
I have transferred the repo to your control. Please let me know if there is anything else that needs to be done for you to move it to the contrib organisation

**Comment by gep13** [comment]
@hawker-am that is great news, thank you!  I will get that transferred over today.

**Comment by gep13** [comment]
@hawker-am I have moved the repository into the Organisation, and yourself and @uber-rob should have received invites to join the Organisation, and once joined, will have the same level of access rights as you did when the repository was hosted under your account.

**Comment by gep13** [comment]
@hawker-am thanks again for doing this!
